package com.mybudgetbuddy.domain.model;

public enum RecommendationType {
    BUDGET_OPTIMIZATION,
    EXPENSE_REDUCTION,
    INCOME_IMPROVEMENT,
    DEBT_MANAGEMENT,
    SAVINGS_OPTIMIZATION,
    INVESTMENT_ADVICE,
    GOAL_ADJUSTMENT,
    EMERGENCY_FUND,
    TAX_OPTIMIZATION,
    CASH_FLOW_IMPROVEMENT,
    RISK_MITIGATION,
    ACCOUNT_MANAGEMENT
}